# Default values for csr-tmf-portal-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
namespace: default
environment: production

# Image configuration
image:
  repository: 025066239748.dkr.ecr.ap-south-1.amazonaws.com/csr-tmf-portal/frontend
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

# Application configuration
config:
  apiUrl: ""
  extraEnvVars: {}

# Deployment configuration
replicaCount: 1

nameOverride: ""
fullnameOverride: ""

# Service Account
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext: {}

# Container security context
securityContext: {}

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits and requests
resources: {}

# Health checks
healthcheck:
  liveness:
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Node selection
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity rules
affinity: {}